
========================================================

This is the automated one for all tp and dose



```{r}
rm(list=ls())

library(stringr)
require(ggplot2)

myPath <- "/home/winks/R_HOME/R_WORK/Bas/official affy analysis/unfiltered genes"
savePath <-"/home/winks/R_HOME/R_WORK/Bas/official affy analysis/selected genes"
myFiles <- dir(myPath)

# gene set:
gene.list.rd <- read.delim(file= "/home/winks/R_HOME/R_WORK/Bas/official affy analysis/selected genes/SelGensBas_1.csv", sep =",", header = F)
colnames(gene.list.rd) <- c("GeneId", "Signalling")


# load all the data in 1 table
gathered.data <- gene.list.rd


allgeneslist <- (buffer$ID[order(buffer$ID)])
allgenes <- (buffer$ID[order(buffer$ID)])
head(allgenes)


n=2
for (i in 1: length( myFiles )) 
  {
n <- n + 1

buffer <- read.table( myFiles[ i ], sep = ",", row.names = 1, header = TRUE )
  head(buffer)
  
zehGenesIndexes<-   match(  allgeneslist, buffer$ID  )
zehGeneListPerCompound<-buffer[ zehGenesIndexes, ]

if ( n ==3) {
allgenes <- as.data.frame(buffer$ID[order(buffer$ID)])
  allgenes$symbols <- zehGeneListPerCompound$syms
  allgenes$GeneID_ma <- zehGeneListPerCompound$entrez_gi
}
allgenes$buffer <- zehGeneListPerCompound$logFC


if (colnames(allgenes)[n+1] != "buffer"){
  stop("jojo")
}
colnames(allgenes)[n+1] <- gsub("corrected_sampleAnot_NF.csv","",  myFiles[i])
head(allgenes)  
      

 print(paste("i is ", i))
    }

head(allgenes)

getwd()
write.table(allgenes, file = "all_genes_bas_.csv", sep = ",", col.names = NA)



gathered.data.noNA <- gathered.data[ !is.na(gathered.data$GeneId), ]

gathered.data$symbols

base <- ggplot(data=ordered, aes(x=trick, y=logFC, fill=DILIConcern )) + 
    geom_bar(colour="white",
             position=position_dodge(),
             size=0.3, stat="identity") + facet_wrap( ~dosetime , ncol=1, scales = "free_x")


cbbPalette <- c("#0072B2", "#000000", "#AA00FFFF", "#D55E00", "#56B4E9", "#009E73", "#F0E442", "#CC79A7", "#E69F00")
base <- base  + scale_fill_manual(values=cbbPalette, name = "DILI-Severity") 

my.title <- unique(as.character(myGene$symbols))

base <- base +  xlab("DILI Compounds") + labs(y=expression(log[2](FC) ) ) + # Set axis labels
    ggtitle(paste ( my.title, sep = "-" )  )   # Set title
      
base <-  base + theme(axis.text.x = element_text( angle = 90, hjust = 1, vjust =0.5, size = 10, colour = "grey50"))  


print(base)


rm("myGene", "ordered")
 
  print(paste("compound printed to file: ", my.title))
}


dev.off()
      

```



wide format
```{r }

m.data <- read.delim("/home/winks/R_HOME/R_WORK/mArray BAC reporter studie/results/gene lists results/BAC targets StevenH Karen/TGP_selection_wide.csv", sep = ",", header = T)

head(m.data)


m.data$treatment.dose.time <- paste(m.data$treatment, m.data$dose, m.data$time, sep =".")
m.data.s <- m.data[, c("logFC","symbols","ENTREZID","treatment.dose.time")]
head(m.data.s)

colnames(m.data.s)

require(reshape)

test <- cast(m.data.s,   symbols  ~  treatment.dose.time , value = "logFC", fun.aggregate = mean )

dim(test)

sum(is.na(test))




#m.data.w <- reshape(m.data.s, v.names = c("treatment.dose.time" ),idvar ="ENTREZID", timevar="",  direction = "wide")
write.table(test, file = "TGP_selection_wide.csv", sep = ",", col.names=NA)
head(test)[,1:10]
?cast

?reshape


dim(m.data.w)


#select part of alread wide format data
ind8h <- grep(".High.8hr",  colnames(m.data))
ind24h <- grep("High.24hr", colnames(m.data))


data.8hr <- m.data[, ind8h]
data.24hr <- m.data[, ind24h]

write.table(data.8hr, file = "/home/winks/R_HOME/R_WORK/mArray BAC reporter studie/results/gene lists results/BAC targets StevenH Karen/TGP_selections_wide_8hrs.csv", sep = ",", col.names = NA  )

write.table(data.24hr, file = "/home/winks/R_HOME/R_WORK/mArray BAC reporter studie/results/gene lists results/BAC targets StevenH Karen/TGP_selections_wide_24hrs.csv", sep = ",", col.names = NA  )


```


# bellow is a bit older code, might still be useable as template
```{r xmassTree}
rm(list=ls())
library(reshape)
library(ggplot2)
library(stringr)
#library(gdata)
myPath<-"/home/winks/R_HOME/R_WORK/Lisa mArray sept 2012/selected genes over all PHH mArrays/results/unfiltered FC and selections/high 24h vsnrma"
myGroups <- read.xls( file.path( "/home/winks/compounds for screen",  "TGPDrugsAnnotatedbyLabel_ForSteven.xls"), sep =",", header = T)
plotTitle <- "DILI_Severity_Genes_high_24hrs"
fileExt <- "_High_24hr_Control_24hr_vsnrma_.csv"


myFiles<- paste(myPath, dir(myPath), sep = "/")

myGroups <- subset( myGroups, select = c("Name_TGP","DILIConcern" ))
myGroups <- myGroups[myGroups$DILIConcern != "", ]

colnames(myGroups)<- c("compound", "DILIConcern")   
myGroups$DILIConcern <-factor(myGroups$DILIConcern)
myGroups$DILIConcern<-factor(myGroups$DILIConcern)
levels(myGroups$DILIConcern)
myGroups$DILIConcern<- gsub("Less-DILI-concern", "Less-DILI-Concern", myGroups$DILIConcern)
myGroups$DILIConcern<- gsub("Most-DILI-concern", "Most-DILI-Concern", myGroups$DILIConcern)
myGroups$DILIConcern<-factor(myGroups$DILIConcern)
levels(myGroups$DILIConcern)
head(myGroups)

myGroups$compound<-factor(myGroups$compound)

#gather data in 1 df

myList = list()
  for (i in 1 : length( myFiles ))
    {
    
    myList[[ i ]] <- read.delim( myFiles[i] , sep =",", header = T)
    myList[[ i ]]$variance <- apply(as.matrix(myList[[i]][,2]), MARGIN = 2, var )
    naamB <- gsub(paste( myPath, "/", sep =""), "", myFiles[ i ])
    naamBB<- gsub(fileExt, "", naamB)
    #naamBBB <- gsub( " ", "",  naamBB )
    #naamBBB <- gsub( "[% + -]", " ",  naamBB )
    #naamBBB <- gsub( ",", "",  naamBB )
    myList[[ i ]]$treatment <- naamBB
    myList[[ i ]] <- subset( myList[[ i ]], select = c("symbols", "logFC", "treatment", "variance"))
    ind <-  myGroups$compound %in% naamBB
    if ( sum( ind ) == 0)  
      {
        myList[[ i ]]$group <- "Unkown"
      
      } else if (sum( ind ) == 1)
        {
        myList[[ i ]]$group <- myGroups$DILIConcern[ ind]  
        } else
          {
            stop ( "mismatch")
          }
    }

  myDF <- do.call( "rbind", myList)
    
        myDFS <- subset(myDF, myDF$group != "Unkown" )
  head(myDF)        
head(myDFS)






#bellow is x-mass tree plotting

ordered <- within(myDFS, { treatment <-reorder(treatment, variance )
                                 group <- reorder(group, -variance)  })
colnames(ordered)



library(ggplot2)

library(RColorBrewer)
myColours <- rep(brewer.pal(8, "Set1"),10 )
length(myColours)
RColorBrewer::display.brewer.all()
cbbPalette <- c("#0072B2", "#000000", "#AA00FFFF", "#D55E00", "#56B4E9", "#009E73", "#F0E442", "#CC79A7", "#E69F00")
myColours <-rep(cbbPalette, 4 )
         length(myColours)       
myColours<-c(myColours, "#0072B2", "#000000", "#AA00FFFF")

groups <- qplot( logFC, treatment, data = ordered,  main = plotTitle)
groups <-groups + facet_grid(group ~ ., scales = "free",
space = "free") 
groups +  theme(strip.text.y = element_text(angle = 0))
?element_text

groups <- groups + aes(shape = symbols) + scale_shape_manual( values = c(25:1, 25:10 ) )  + aes(color = symbols) +
scale_color_manual( values = myColours ) 
groups <- groups + theme(strip.text.y = element_text(180))
groups + labs(x=expression(log[2](FC) ) )

groups + xlim(-2,2)

write.table(myDFS, file = paste("/home/winks/R_HOME/R_WORK/selections results march 2013/PHH/NRF2 NFkB and apoptosis summary","relaHits_screen_results.csv", sep = "/"), sep =",", col.names=NA)


groups <- groups + xlim(-2, 2.5)

groups


groups + aes( size = symbols ) + scale_size_manual( values = c(1, 1,2,1,1 ,rep(  1, 3 ), 1,1, 1,2,2,2,  rep(1,5),2, rep(1,12),1,1,2,1)    ) + aes(color = symbols) + scale_colour_manual(values = myColours) + aes(shape = symbols) + scale_shape_manual(values =c(25:1, 25:14  )  ) + coord_cartesian(xlim = c(-2,2))







groups <- qplot( logFC, treatment, data = ordered,  alpha=I(1/2), main = "TGP BAC PHH 24 hour high dose")
groups <-groups + facet_grid(group ~ ., scales = "free",
space = "free") + theme(strip.text.y = element_text())

library(RColorBrewer)
myColours <- rep(brewer.pal(8, "Set1"),5 )
RColorBrewer::display.brewer.all()

?brewer
groups + aes( size = symbols ) + scale_size_manual( values = c(1, 1,2,1,1 ,rep(  1, 3 ), 1,1, 1,2,2,2,  rep(1,5),2, rep(1,12),1,1,2,1)    ) + aes(color = symbols) + scale_colour_manual(values = myColours) + aes(shape = symbols) + scale_shape_manual(values =c(25:1, 25:14  )  ) + coord_cartesian(xlim = c(-2,2))

# 

#c("red", "orange", "blue", "green", "blue","red", "orange", "yellow", "green", "blue","red", "orange", "yellow", "green", "blue","red", "orange", "yellow", "green", "blue","red", "orange", "yellow", "green", "blue","red", "orange", "yellow", "green", "blue","red", "orange", "yellow", "green", "blue", "blue")








#ATF4 EIF4A1 EIF4A2 EIF4G3 HSPA5 XBP1 SRXN1 DDIT3
selGenes <- c("ATF4", "EIF4A1", "EIF4A2", "EIF4G3", "HSPA5", "XBP1", "SRXN1", "DDIT3")

for ( j in 1 : length(selGenes))
  {

  myGene <- subset( myDFS, myDFS$symbols == selGenes[ j ] )
  myGene <- subset( myGene, myGene$group != "No-DILI-Concern")

  ordered<-within(myGene, { treatment <-reorder(treatment, logFC )
                                 group <- reorder(group, -logFC)  })

base <- ggplot(data=ordered, aes(x=treatment, y=logFC, fill=group )) + 
    geom_bar(colour="white",
             position=position_dodge(),
             size=0.3, stat="identity") 


cbbPalette <- c("#0072B2", "#000000", "#AA00FFFF", "#D55E00", "#56B4E9", "#009E73", "#F0E442", "#CC79A7", "#E69F00")
base <- base  + scale_fill_manual(values=cbbPalette[c(3,7) ], name = "DILI-Severity") 
   

base <- base +  xlab("DILI Compounds") + labs(y=expression(log[2](FC) ) ) + # Set axis labels
    ggtitle(paste (plotTitle, selGenes[ j ], sep = "-" )  )   # Set title
      
base <-  base + theme(axis.text.x = element_text( angle = 90, hjust = 1, vjust =0.5, size = 10, colour = "grey50"))  

#pdf( paste( plotTitle, selGenes[j], sep = "-"), height = 10, width = 15  )
print(base)

dev.off()

}
geel
"#F0E442",
paars:
  "#AA00FFFF",

alsVoorbeeld <- c("#AA00FFFF","#AA00FFFF","#F0E442","#AA00FFFF","#AA00FFFF","#AA00FFFF","#F0E442","#F0E442","#F0E442","#AA00FFFF","#AA00FFFF","#F0E442","#F0E442","#F0E442","#F0E442","#F0E442","#F0E442","#F0E442","#AA00FFFF","#F0E442","#F0E442","#F0E442","#F0E442","#F0E442","#F0E442","#F0E442","#AA00FFFF","#F0E442","#F0E442","#AA00FFFF","#AA00FFFF","#F0E442","#F0E442","#F0E442","#F0E442","#F0E442","#F0E442",  "#AA00FFFF",  "#AA00FFFF","#F0E442","#AA00FFFF","#AA00FFFF","#AA00FFFF","#F0E442","#F0E442","#AA00FFFF","#AA00FFFF","#AA00FFFF","#AA00FFFF","#AA00FFFF","#AA00FFFF","#AA00FFFF","#AA00FFFF","#F0E442","#AA00FFFF","#AA00FFFF","#F0E442","#F0E442","#F0E442","#AA00FFFF","#F0E442","#F0E442","#F0E442","#AA00FFFF","#AA00FFFF","#AA00FFFF","#AA00FFFF","#F0E442","#AA00FFFF","#AA00FFFF","#F0E442","#F0E442","#F0E442","#F0E442","#AA00FFFF","#F0E442","#F0E442","#F0E442","#F0E442","#AA00FFFF","#AA00FFFF","#AA00FFFF","#AA00FFFF","#AA00FFFF","#F0E442","#F0E442","#F0E442","#F0E442","#AA00FFFF","#F0E442","#F0E442","#AA00FFFF","#AA00FFFF","#F0E442","#F0E442","#AA00FFFF","#F0E442","#AA00FFFF","#AA00FFFF")


alsVoorbeeld





#some older maybe usefull code snippets


#plot for lisa: number of compounds that induce at least e.g. 25% of genes at level fold change 2 per DILI group
head(myDFS)
length(unique(myDFS$treatment))
length(myDFS$treatment)

head(myData24hFC_long1)

condTest <- function(x) sum( x > log2(1.5) ) >5
myTest <- by( data=myData24hFC_long1$FC, FUN = condTest, INDICES = as.factor( myData24hFC_long1$Treatment ) ) 
sum(myTest)
class(myTest)
myTestDF<- as.data.frame(myTest[1 : length(unique(myData24hFC_long1$Treatment )) ])
myTestDF$treatment <- rownames(myTestDF)


ind<-match(unique(myData24hFC_long1$Treatment),myData24hFC_long1$Treatment)
aggr <- myData24hFC_long1[ind,]
nrow(aggr)==length(unique(myData24hFC_long1$Treatment))
colnames(aggr)[2]<-"treatment"
aggrE <-merge( x=myTestDF,y= aggr, by = "treatment" )    

colnames(aggrE)[2] <- "test"



aggrEL <- aggregate( test ~ group, data = aggrE,  sum    )



myF<-function(x) length(levels(factor(x)))
  toNorm <- by(data = myData24hFC_long1$Treatment, FUN =myF, INDICES = as.factor(myData24hFC_long1$group) )
    toNorm<-as.data.frame(toNorm[ 1 : length(unique(myData24hFC_long1$group ))])
      colnames(toNorm)<-"nCompounds"
aggrC<- cbind(aggrEL, toNorm)
aggrCS <- aggrC[-1,]    
  qplot(x = group, y = test/nCompounds, data = aggrCS) + geom_histogram(stat = "identity") 









g ordered_8h<-with(myData8hFC_long, reorder( Treatment , variance) );
g ordered_24h<-with(myData24hFC_long, reorder( Treatment , variance) );
change names
plot<-qplot( FC, ordered_8h, data = myData8hFC_long, fill = symbols, color = symbols, alpha=I(1/2) ) 
g plot<- plot + aes(shape = symbols) + scale_shape_manual( values = c(1:25, 1:9)) 
g plot <- plot + facet_grid(group ~ ., scales = "free",
g space = "free") + theme(strip.text.y = element_text())
g plot
last_plot() + aes( size = symbols ) + scale_size_manual( values = c(1, 1,3,1,1 ,rep(  1, 3 ), 1,1, 1,3,3,3,  rep(1,5),3, rep(1,12),1,1,3,1)    ) + aes(color = symbols) + scale_colour_manual(values = c("red", "orange", "yellow", "green", "blue","red", "orange", "yellow", "green", "blue","red", "orange", "yellow", "green", "blue","red", "orange", "yellow", "green", "blue","red", "orange", "yellow", "green", "blue","red", "orange", "yellow", "green", "blue","red", "orange", "yellow", "green", "blue", "blue"))
g plot<-qplot( FC, ordered_24h, data = myData24hFC_long, fill = symbols, color = symbols, alpha=I(1/2)  )
g plot<- plot + aes(shape = symbols) + scale_shape_manual( values = c(1:25, 1:9))
plot


```

